### ISSUE TITLE
when will the pre-trained model be available

### ISSUE THREAD

**Issue by QiukuZ** [jytime/Deep-SfM-Revisited#1]
Helloooooooo!
Great job!!!!!!
Hope to see the pre-trained model and more complete code soon!!

**Comment by jytime** [comment]
Hi Qiuku,

I am dealing with another project, but I guess the left could be released this or next week. Please let me know if you are particularly interested in some parts.

Best

**Comment by QiukuZ** [comment]
Great!!!!!!
