### ISSUE TITLE
essential_matrix' has no attribute 'initialise'

### ISSUE THREAD

**Issue by nivesh48** [jytime/Deep-SfM-Revisited#13]
I've installed essential_matrix module as per the README file, i am able to import the module. However, i ran into "essential_matrix' has no attribute 'initialise'" 

My installation process was successful.  Could you provide some leads on how to solve this?

Thank you

**Comment by HencyChen** [comment]
Hi @nivesh48 
I've also followed the installation guide provided by author. However, I cannot import the essential_matrix, do you have any idea of this?
