### ISSUE TITLE
Pre-trained posenet

### ISSUE THREAD

**Issue by tmpss93172** [jytime/Deep-SfM-Revisited#17]
Great work!

Could you release your pre-trained Posenet model trained on KITTI?

Thanks!

**Comment by jytime** [comment]
Hi, I currently cannot get access to the previous server to download the pre-trained posenet model, which is a ablation of our work. Given a pose prediction network is popular in deep sfm methods, possibly you may refer to other methods using posecnn on KITTI.

Best
