### ISSUE TITLE
Missing dependencies in requirements.txt like minieigen

### ISSUE THREAD

**Issue by SvenDierfeld** [jytime/Deep-SfM-Revisited#18]
Hello,

Not all dependencies are listed in the requirements.txt. Specifically, I have problems installing minieigen. How do you install the package and which version do you use? sudo apt-get python3-minieigen installs a version for python 3.8. I found no other way but potentially building it from source. Is that right?

**Comment by jytime** [comment]
Hi,

We could install minieigen by pip, like shown [here](https://package.wiki/minieigen). It should work with 0.5+, and I would double check the version later. 

By the way, minieigen is only used for calculating the metrics on Demon. You could just remove the file `demon_metrics.py' if it is not desired.

**Comment by SvenDierfeld** [comment]
Hello,

thank you for answering. So it seems to be a problem with pip and minieigen, so I had to to uncomment the parts that use the _compute_motion_errors_ function from the _demon_metrics.py_.

**Comment by jytime** [comment]
You can also refer to [this](https://github.com/weixk2015/DeepSFM/issues/8), which lists some possible solutions for this problem, but could be kind of complicated.
