### ISSUE TITLE
Abouth the usage of cfg.NORM_TARGET

### ISSUE THREAD

**Issue by xhchen10** [jytime/Deep-SfM-Revisited#19]
Hi, thanks for sharing the impressive work.

After browsing the code, I am confused about a hyper-parameter NORM_TARGET. Could you kindly explain the usage of this hyper-parameter?

Thanks.

**Comment by xhchen10** [comment]
The hyper-parameter NORM_TARGET seems related to the alpha in the paper. How to set it if one applies the method to other datasets?

**Comment by jytime** [comment]
Hi, it can be computed as the statistic of the training dataset. Normally, you could use the default number for most datasets.

**Comment by xhchen10** [comment]
Thanks for the reply. :)
