### ISSUE TITLE
Oracle Pose

### ISSUE THREAD

**Issue by LeoPerelli** [jytime/Deep-SfM-Revisited#21]
Hey @jytime, thanks for sharing your work!

I was trying to replicate your experiments using the grountruth pose on KITTI, which should provide the upper bound for your method. I used the `GT_POSE` and `GT_POSE_NORMALIZED` flags to perform inference with gt poses.
For some reason, the performance is much worse than when estimating the pose with `RANSAC`, which I am instead able to replicate. Can you provide some guidance on what might be the problem? 

Thanks a lot!

**Comment by jytime** [comment]
Hi,

Thanks for your interest. I would recommend if you could check the code in https://github.com/jytime/Deep-SfM-Revisited/blob/6ebae04e5a9272d7ae118f4609b5529a72e01edc/models/SFMnet.py#L107-155, which should be directly related

Best,
Jianyuan

**Comment by LeoPerelli** [comment]
Hey, thanks a lot! It actually turned out to be a problem related to a few poses which were totally off and perturbed the results, closing this one!
