### ISSUE TITLE
About KITTI files

### ISSUE THREAD

**Issue by Wavelet-jc** [jytime/Deep-SfM-Revisited#23]
Hi, thank you for your paper contribution.

I'm sorry to bother you. when I reproduced the code program I can't find these files (train_files. txt, test_files.txt, kitti_raw_calib_dict.npy, kitti_raw_calib_dict.npy) . But I only find calib_cam_to_cam.txt. Do I need to make certain data format conversion?

Can you tell me the correct way find them or the source of these files. 
Thanks!

```python
class KITTIRAWLoaderGT(data.Dataset):
    def __init__(self, root, transform=None, target_transform=None, co_transform=None, train=True):
        train_files = os.path.join(self.root, 'train_files.txt')
        test_files = os.path.join(self.root, 'test_files.txt')
        self.calib_dict = np.load(os.path.join(self.root, 'kitti_raw_calib_dict.npy'), allow_pickle=True).item()
```

**Comment by jytime** [comment]
Hi,

We provided the split files in the Readme. You can download them from https://drive.google.com/drive/folders/1g0uoNrldySyWnkVfQ53etqcNlhzJrAHx. It is named as kitti_splits.zip

**Comment by Wavelet-jc** [comment]
Thank you! @jytime
