### ISSUE TITLE
about eigen sfm splits 

### ISSUE THREAD

**Issue by henry123-boy** [jytime/Deep-SfM-Revisited#3]
can u provide the eigne sfm splits?

**Comment by jytime** [comment]
It has been provided in the 'kitti_splits.zip'. Please refer to https://github.com/jytime/Deep-SfM-Revisited/blob/903867c8de8f309906b767b77e2c2fc27f406350/KITTI_loader.py#L294-L299 for details.

Best,
Jianyuan
