### ISSUE TITLE
About KITTI gt depth 

### ISSUE THREAD

**Issue by longyangqi** [jytime/Deep-SfM-Revisited#7]
Great work!
I am confused about the  `gt_depth_dir `.
- Which gt depth of KITTI  should  we use to reproduce the results (absrel around 0.053 and rmse close to 2.22) ?   The `raw velodyne_points` (*.bin) in KITTI RAW data, the projected  velodyne_raw (*.png) or the  groundtruth (*.png) in 14GB official depth maps?  I guess it would be   `raw velodyne_points` (*.bin) ?
- But, then what is the usage of 14GB official depth maps?

Looking forward to your reply!
Thanks!

**Comment by jytime** [comment]
Hi,

Following the previous work, we use the official depth for training and evaluation. It is worth noting that KITTI does not provide official depth for all images in the Eigen val split (697).  Therefore, we use raw lidar for evaluation if official depth is not available. This is for the consistency with the previous works like DORN. In either setting, our performance relative to other methods is stable.

Best
