### ISSUE TITLE
run demon.py and evaluate.py cause same errors

### ISSUE THREAD

**Issue by wangxiyuan9** [jytime/Deep-SfM-Revisited#9]
Hello , thanks great work,@jytime  
I  do as your README said , when run  demo.py and evaluate.py in model.RAFT , but cause some issues 
run demo.py 
![run_demo_errors](https://user-images.githubusercontent.com/84949506/146634390-6d946e5d-5eec-4aaa-ba4d-fcea6a3cb82b.png)
I already download the Sintel of dataset and  download_models.,but when i  try python evaluate.py --model=models/raft-things.pth --dataset=sintel --mixed_precision.it has some errors ,.
run evaluate.py errors
![2021-12-18 16-15-27 的屏幕截图](https://user-images.githubusercontent.com/84949506/146634599-33433742-b5c1-44b4-bea0-6297868beaf0.png)
i found this cause by evaluate.py in line 116 for "flow_low, flow_pr = model(image1, image2, iters=iters, test_mode=True)",seems only one image could as parameter otherwise cause such errors  as error  picture  shows. But change it also don't work . I could not solve it  , could you give me some advice ? thanks very much 
My environment : ubuntu20.04    cuda:11.1(RTX3060 needsotherwise error)  torch==1.8.0   , other satisfy README.md

**Comment by jytime** [comment]
Hi,

The script demo.py and evaluate.py come from the repository https://github.com/princeton-vl/RAFT. They were designed for RAFT visualization and evaluation, but not our method. I just kept them for completeness. I will delete them later.

Best

**Comment by 3196887235** [comment]
Hello ,  @jytime Thank you for your answer , so the Deep-SfM-Revisited  project  doesn't need to do demo.py and evaluate.py  in RAFT project , right? I just want to know these errors whether  affect this project .
In addition ,I also have problem for raw data download ,could you give me some advice for [https://github.com/jytime/Deep-SfM-Revisited/issues/8](url).
Here is its photo
![2021-12-18 22-22-45 的屏幕截图](https://user-images.githubusercontent.com/84949506/146644351-1154b935-535d-4d2c-bf41-9facf2b092ce.png)
Thanks
